export const ERROR_CODES = {
  // Auth
  NO_TOKEN: 'NO_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  EMAIL_EXISTS: 'EMAIL_EXISTS',

  // Tenant
  TENANT_REQUIRED: 'TENANT_REQUIRED',
  TENANT_SUSPENDED: 'TENANT_SUSPENDED',
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',

  // Permissions
  FORBIDDEN: 'FORBIDDEN',
  NOT_AUTHENTICATED: 'NOT_AUTHENTICATED',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  // Rate limit
  RATE_LIMITED: 'RATE_LIMITED',

  // General
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;
